[tool.poetry]
name = "zielerfassung"
version = "0.1.0"
description = "CLI tool for goal management and tracking"
authors = ["Your Name <youremail@example.com>"]
dependencies = [
    "click = "^8.0"",
    "sqlalchemy = "^1.4""
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
